version: '3'
services:
  app:
    build: .
    ports:
      - 8082:8082
    volumes:
      - .:/go/src/youtuerp
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe123
      MYSQL_DATABASE: go_youtuerp
    volumes:
      - /var/run/mysqld


