version: '3'
services:
  app:
    build: .
    ports:
      - 8082:8082
    volumes:
      - .:/go/src/youtuerp
    depends_on:
      - db
    networks:
      - mynet
    tty: true
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe123
      MYSQL_DATABASE: go_youtuerp
    networks:
      - mynet
networks:
  mynet:
    driver: "bridge"
